<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">clearMemory</value>
  <value name="encodeutf8">true</value>
  <value name="body">CgkvLyBNZW1vcnkgaXMgYSBWYWx1ZXMgb2JqZWN0IHRoYXQgY29uc2lzdHMgb2YgbmFtZS92YWx1
ZSBwYWlycy4gIEJlbG93CgkvLyB3ZSBhcmUgZ2V0dGluZyBhbGwgb2YgdGhlIG5hbWVzIChrZXlz
KSBzdG9yZWQgaW4gdGhlIE1lbW9yeSBvYmplY3QKCS8vIGFuZCB0aGVuIGxvb3AgdGhyb3VnaCB0
aGVtIHJlbW92aW5nIHRoZSB2YWx1ZXMgb25lIGF0IGEgdGltZSB1bnRpbAoJLy8gdGhlIGFyZSBh
bGwgZ29uZS4KCUVudW1lcmF0aW9uIGtleXMgPSBNZW1vcnkua2V5cygpOw0KCQoJaWYgKGtleXMg
IT0gbnVsbCkKCXsNCiAJCXdoaWxlIChrZXlzLmhhc01vcmVFbGVtZW50cygpKQoJCXsNCgkJCU1l
bW9yeS5yZW1vdmUoKFN0cmluZykga2V5cy5uZXh0RWxlbWVudCgpKTsNCgkJfQ0KICAgIA0KCX0N
</value>
</Values>
