<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">splitLimit</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gVG9uaSBJbW1vcmRpbm8KCi8vIHBpcGVsaW5lCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29y
ID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7ClN0cmluZyByZWdleCA9IElEYXRhVXRpbC5nZXRTdHJp
bmcoIHBpcGVsaW5lQ3Vyc29yLCAicmVnZXgiICk7ClN0cmluZyBpbnB1dCA9IElEYXRhVXRpbC5n
ZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiaW5wdXQiICk7ClN0cmluZyBsaW1pdCA9IElEYXRh
VXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAibGltaXQiICk7CnBpcGVsaW5lQ3Vyc29y
LmRlc3Ryb3koKTsKClBhdHRlcm4gcGF0dGVybiA9IFBhdHRlcm4uY29tcGlsZShyZWdleCk7CgpT
dHJpbmcgaXRlbXNbXSA9IHBhdHRlcm4uc3BsaXQoaW5wdXQsIEludGVnZXIucGFyc2VJbnQobGlt
aXQpKTsKZm9yIChpbnQgaT0wOyBpIDwgaXRlbXMubGVuZ3RoOyBpKyspCnsKCVN5c3RlbS5vdXQu
cHJpbnRsbihpdGVtc1tpXSk7Cn0KCi8vIHBpcGVsaW5lCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vy
c29yXzEgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJz
b3JfMSwgIml0ZW1zIiwgaXRlbXMgKTsKcGlwZWxpbmVDdXJzb3JfMS5kZXN0cm95KCk7Cg==</value>
</Values>
