<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">convertLineSeparator</value>
  <value name="encodeutf8">true</value>
  <value name="body">CglJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoKCVN0cmlu
ZyBpblN0cmluZyA9IG51bGw7CglpZiAoaWRjUGlwZWxpbmUuZmlyc3QoImluU3RyaW5nIikpCgl7
CgkJaW5TdHJpbmcgPSAoU3RyaW5nKWlkY1BpcGVsaW5lLmdldFZhbHVlKCk7Cgl9CgllbHNlCgl7
CgkJLy8gSW5wdXQgc3RyaW5nIGlzIG51bGwuICBEbyBub3RoaW5nCgkJcmV0dXJuOwoJfQoKCVN0
cmluZyBvdXRTdHJpbmcgPSAiIjsKCglTdHJpbmcgbGluZVNlcGFyYXRvciA9IFN5c3RlbS5nZXRQ
cm9wZXJ0eSgibGluZS5zZXBhcmF0b3IiKTsKCglpbnQgY3VyckluZGV4ID0gMDsKCWludCBwcmV2
SW5kZXggPSAwOwoJd2hpbGUgKChjdXJySW5kZXggPSBpblN0cmluZy5pbmRleE9mKCdcbicsY3Vy
ckluZGV4KSkhPSAtMSkKCXsKCQkvLyBJZiB0aGlzIGlzIHBhcnQgb2YgXHJcbiwgdGhlbiBkb24n
dCByZXBsYWNlCgkJaWYgKChjdXJySW5kZXggIT0gMCkgJiYgKGluU3RyaW5nLmNoYXJBdChjdXJy
SW5kZXggLSAxKSA9PSAnXHInKSkKCQl7CgkJCWN1cnJJbmRleCA9IGN1cnJJbmRleCArIDE7CgkJ
fQoJCWVsc2UKCQl7CgkJCW91dFN0cmluZyA9IG91dFN0cmluZyArIGluU3RyaW5nLnN1YnN0cmlu
ZyhwcmV2SW5kZXgsY3VyckluZGV4KSArIGxpbmVTZXBhcmF0b3I7CgkJCXByZXZJbmRleCA9IGN1
cnJJbmRleCArIDE7CgkJCWN1cnJJbmRleCA9IGN1cnJJbmRleCArIDE7CgkJfQoJfQoJb3V0U3Ry
aW5nID0gb3V0U3RyaW5nICsgaW5TdHJpbmcuc3Vic3RyaW5nKHByZXZJbmRleCk7CgoJaWRjUGlw
ZWxpbmUuaW5zZXJ0QWZ0ZXIoIm91dFN0cmluZyIsIG91dFN0cmluZyk7CgovLyBDbGVhbiB1cCBJ
RGF0YSBjdXJzb3JzCglpZGNQaXBlbGluZS5kZXN0cm95KCk7Cg==</value>
</Values>
