<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">isDate</value>
  <value name="encodeutf8">true</value>
  <value name="body">CglJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoJcGlw
ZWxpbmVDdXJzb3IuZmlyc3QoICJpbnB1dCIgKTsKCVN0cmluZyBpbnB1dCA9IChTdHJpbmcpcGlw
ZWxpbmVDdXJzb3IuZ2V0VmFsdWUoKTsKCXBpcGVsaW5lQ3Vyc29yLmZpcnN0KCAiZGF0ZUZvcm1h
dCIgKTsKCVN0cmluZyBkYXRlRm9ybWF0ID0gKFN0cmluZylwaXBlbGluZUN1cnNvci5nZXRWYWx1
ZSgpOwoKCVN0cmluZyBpc0RhdGUgPSAidHJ1ZSI7CgoJdHJ5Cgl7CgkJLy8gRm9ybWF0IHRoZSBj
dXJyZW50IHRpbWUuCgkJU2ltcGxlRGF0ZUZvcm1hdCBzZGY7CgkJaWYgKGRhdGVGb3JtYXQgPT0g
bnVsbCB8fCBkYXRlRm9ybWF0LmVxdWFscygiIikpCgkJewoJCQlzZGYgPSBuZXcgU2ltcGxlRGF0
ZUZvcm1hdCAoInl5eXktTU0tZGQgSEg6bW06c3MiKTsKCQl9CgkJZWxzZQoJCXsKCQkJc2RmID0g
bmV3IFNpbXBsZURhdGVGb3JtYXQgKGRhdGVGb3JtYXQpOwoJCX0JCQoJCXNkZi5zZXRMZW5pZW50
KGZhbHNlKTsKCgkJRGF0ZSBwYXJzZWREYXRlID0gc2RmLnBhcnNlKGlucHV0KTsKCX0KCWNhdGNo
IChFeGNlcHRpb24gZSkKCXsKCQlpc0RhdGUgPSAiZmFsc2UiOwoJfQoKCXBpcGVsaW5lQ3Vyc29y
Lmluc2VydEFmdGVyKCJpc0RhdGUiLCBpc0RhdGUpOwoJcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgp
OwoK</value>
</Values>
