<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">roundNumber</value>
  <value name="encodeutf8">true</value>
  <value name="body">CglJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoJaWYgKCFp
ZGNQaXBlbGluZS5maXJzdCgibnVtYmVyIikpCgl7CgkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRp
b24oImlucHV0IG51bWJlciB3YXMgbnVsbCEiKTsKCX0KCglTdHJpbmcgc3RyTnVtYmVyID0gKFN0
cmluZylpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOwoJZG91YmxlIGRibE51bWJlciA9IERvdWJsZS5w
YXJzZURvdWJsZShzdHJOdW1iZXIpOwoKCglpZiAoaWRjUGlwZWxpbmUuZmlyc3QoInByZWNpc2lv
biIpKQoJewoJCVN0cmluZyBzdHJQcmVjaXNpb24gPSAoU3RyaW5nKWlkY1BpcGVsaW5lLmdldFZh
bHVlKCk7CgkJZG91YmxlIGRibFByZWNpc2lvbiA9IERvdWJsZS5wYXJzZURvdWJsZShzdHJQcmVj
aXNpb24pOwoKCQlkb3VibGUgZGJsTXVsRGl2RmFjdG9yID0gamF2YS5sYW5nLk1hdGgucG93KDEw
LCBkYmxQcmVjaXNpb24pOwoJCWRvdWJsZSBkYmxSb3VuZGVkTnVtYmVyID0gamF2YS5sYW5nLk1h
dGgucm91bmQoZGJsTnVtYmVyICogZGJsTXVsRGl2RmFjdG9yKSAvIGRibE11bERpdkZhY3RvcjsK
CgkJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInJvdW5kZWROdW1iZXIiLCBEb3VibGUudG9TdHJp
bmcoZGJsUm91bmRlZE51bWJlcikpOwoKCX0KCWVsc2UKCXsKCQlpZGNQaXBlbGluZS5pbnNlcnRB
ZnRlcigicm91bmRlZE51bWJlciIsIHN0ck51bWJlcik7CgoJfQoKCWlkY1BpcGVsaW5lLmRlc3Ry
b3koKTs=</value>
</Values>
