<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getParameterValue</value>
  <value name="encodeutf8">true</value>
  <value name="body">CglJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoJU3RyaW5n
IHN0clBhcmFtTmFtZSA9IG51bGw7CglpZiAoaWRjUGlwZWxpbmUuZmlyc3QoInBhcmFtTmFtZSIp
KQoJewoJCXN0clBhcmFtTmFtZSA9IChTdHJpbmcpaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsKCX0K
CWVsc2UKCXsKCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbiAoIlBhcmFtZXRlciBuYW1lIGNh
bm5vdCBiZSBudWxsISIpOwoJfQoKCVN0cmluZyBzdHJQYXJhbVZhbHVlID0gKFN0cmluZylwcm9w
ZXJ0aWVzLmdldChzdHJQYXJhbU5hbWUpOwoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInBhcmFt
VmFsdWUiLCBzdHJQYXJhbVZhbHVlKTsKCWlkY1BpcGVsaW5lLmRlc3Ryb3koKTsKCg==</value>
</Values>
