<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getRemoteServerInfoHelper</value>
  <value name="encodeutf8">true</value>
  <value name="body">CglWYWx1ZXMgc2VydmVycyA9IGluLmdldFZhbHVlcygic2VydmVycyIpOwoJU3RyaW5nIGFsaWFz
ID0gaW4uZ2V0U3RyaW5nKCJhbGlhcyIpOwoKCVZhbHVlcyBzZXJ2ZXJJbmZvID0gc2VydmVycy5n
ZXRWYWx1ZXMoYWxpYXMpOwoKCWlmIChzZXJ2ZXJJbmZvID09IG51bGwpCgl7CgkJb3V0ID0gU2Vy
dmljZS50aHJvd0Vycm9yKCJSZW1vdGUgc2VydmVyIGFsaWFzIFwiIiArIGFsaWFzICsgIlwiIGRv
ZXMgbm90IGV4aXN0LiIpOwoJCXJldHVybiBvdXQ7Cgl9CgoJU3RyaW5nIGhvc3QgPSBzZXJ2ZXJJ
bmZvLmdldFN0cmluZygiaG9zdCIpOwoJU3RyaW5nIHBvcnQgPSBzZXJ2ZXJJbmZvLmdldFN0cmlu
ZygicG9ydCIpOwoJU3RyaW5nIHVzZXIgPSBzZXJ2ZXJJbmZvLmdldFN0cmluZygidXNlciIpOwoJ
U3RyaW5nIHBhc3MgPSBzZXJ2ZXJJbmZvLmdldFN0cmluZygicGFzcyIpOwoJU3RyaW5nIHNzbCA9
IHNlcnZlckluZm8uZ2V0U3RyaW5nKCJzc2wiKTsKCVN0cmluZyBwcml2S2V5RmlsZSA9IHNlcnZl
ckluZm8uZ2V0U3RyaW5nKCJwcml2S2V5RmlsZSIpOwoJU3RyaW5nIGNlcnRGaWxlcyA9IHNlcnZl
ckluZm8uZ2V0U3RyaW5nKCJjZXJ0RmlsZXMiKTsKCglvdXQucHV0KCJob3N0IiwgaG9zdCk7Cglv
dXQucHV0KCJwb3J0IiwgcG9ydCk7CglvdXQucHV0KCJ1c2VyIiwgdXNlcik7CglvdXQucHV0KCJw
YXNzIiwgcGFzcyk7CglvdXQucHV0KCJzc2wiLCBzc2wpOwoJb3V0LnB1dCgicHJpdktleUZpbGUi
LCBwcml2S2V5RmlsZSk7CglvdXQucHV0KCJjZXJ0cyIsIGNlcnRGaWxlcyk7Cg==</value>
</Values>
