<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">removeObjectFromSession</value>
  <value name="encodeutf8">true</value>
  <value name="body">CglJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoJU3RyaW5n
IHN0ck9iamVjdE5hbWUgPSAiIjsKCWlmIChpZGNQaXBlbGluZS5maXJzdCgib2JqZWN0TmFtZSIp
KQoJewoJCXN0ck9iamVjdE5hbWUgPSAoU3RyaW5nKWlkY1BpcGVsaW5lLmdldFZhbHVlKCk7Cgl9
CgllbHNlCgl7CgkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24gKCJvYmplY3ROYW1lIGlzIG51
bGwhIik7Cgl9CgoJU2Vzc2lvbiBzZXNzaW9uID0gU2VydmljZS5nZXRTZXNzaW9uKCk7CglPYmpl
Y3Qgb2JqID0gc2Vzc2lvbi5yZW1vdmUoc3RyT2JqZWN0TmFtZSk7CgoJaWRjUGlwZWxpbmUuaW5z
ZXJ0QWZ0ZXIoIm9iamVjdCIsIG9iaik7CgoJaWRjUGlwZWxpbmUuZGVzdHJveSgpOwo=</value>
</Values>
