<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">loadPSUtilitiesConfig</value>
  <value name="encodeutf8">true</value>
  <value name="body">CXRyeQoJewovLwkJU3RyaW5nIHN0ckZpbGVTZXBhcmF0b3IgPSAoU3lzdGVtLmdldFByb3BlcnRp
ZXMoKSkuZ2V0UHJvcGVydHkoImZpbGUuc2VwYXJhdG9yIik7CQovLwkJU3RyaW5nIHN0ckN1cnJl
bnREaXIgPSAoU3lzdGVtLmdldFByb3BlcnRpZXMoKSkuZ2V0UHJvcGVydHkoInVzZXIuZGlyIik7
CQoJCVN0cmluZyBzdHJGaWxlbmFtZSA9ICJwYWNrYWdlcy9QU1V0aWxpdGllcy9jb25maWcvUFNV
dGlsaXRpZXMuY25mIjsKCgkJRmlsZSBmaWxlID0gbmV3IEZpbGUoc3RyRmlsZW5hbWUpOwoJCWlm
IChmaWxlLmNhblJlYWQoKSkKCQl7CgkJCUlucHV0U3RyZWFtIHN0cmVhbSA9IG5ldyBqYXZhLmlv
LkJ1ZmZlcmVkSW5wdXRTdHJlYW0obmV3IGphdmEuaW8uRmlsZUlucHV0U3RyZWFtKGZpbGUpKTsK
CgkJCXRyeQoJCQl7CgkJCQlwcm9wZXJ0aWVzLmxvYWQoc3RyZWFtKTsKCQkJCVN5c3RlbS5vdXQu
cHJpbnRsbigiU3VjY2Vzc2Z1bGx5IGxvYWRlZCBQU1V0aWxpdGllcyBjb25maWd1cmF0aW9uIGZp
bGUgaW50byBtZW1vcnkiKTsKCQkJfQoJCQlmaW5hbGx5CgkJCXsKCQkJCXN0cmVhbS5jbG9zZSgp
OwoJCQl9CgoJCX0KCQllbHNlCgkJewoJCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiQ291
bGQgbm90IHJlYWQgcHJvcGVydGllcyBmaWxlOiAiICsgc3RyRmlsZW5hbWUpOwoJCX0KCX0KCWNh
dGNoKCBFeGNlcHRpb24gZSApCgl7CgkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIkVycm9y
IHJlYWRpbmcgcHJvcGVydGllcyBmaWxlOiAiICsgZSk7Cgl9Cgo=</value>
</Values>
