<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">listKeysInMemory</value>
  <value name="encodeutf8">true</value>
  <value name="body">CS8vIEdldCBjdXJzb3Igb24gcGlwZWxpbmUgb2JqZWN0IGZvciBkYXRhIG1hbmlwdWxhdGlvbgoJ
SURhdGFDdXJzb3IgaWRjUGlwZWxpbmUgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCgkvLyBHZXRz
IGEgbGlzdCBvZiBhbGwgb2YgdGhlIGtleXMgYW5kIHBsYWNlcyB0aGVtIGluIGEgU3RyaW5nW10K
CUVudW1lcmF0aW9uIGtleXMgPSBNZW1vcnkua2V5cygpOw0KCWlmIChrZXlzICE9IG51bGwpCgl7
DQoJCVZlY3RvciBpZFZlY3RvciA9IG5ldyBWZWN0b3IoKTsNCgkJd2hpbGUgKGtleXMuaGFzTW9y
ZUVsZW1lbnRzKCkpCgkJew0KCQkJU3RyaW5nIGlkID0gKFN0cmluZykga2V5cy5uZXh0RWxlbWVu
dCgpOw0KCQkJaWRWZWN0b3IuYWRkRWxlbWVudChpZCk7DQoJCX0NCgkgICAgDQogICAgIAlpbnQg
aWRDb3VudCA9IGlkVmVjdG9yLnNpemUoKTsNCgkgCWlmIChpZENvdW50ID4wKQoJIAl7CQ0KCQkJ
U3RyaW5nW10gTWVtb3J5S2V5cyA9IG5ldyBTdHJpbmdbaWRDb3VudF07DQoJCQlpZFZlY3Rvci5j
b3B5SW50byhNZW1vcnlLZXlzKTsNCgkJCQoJCQkvLyBQdXQgZGF0YSBpbnRvIHBpcGVsaW5lCgkJ
CWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJNZW1vcnlLZXlzIiwgTWVtb3J5S2V5cyk7CgkgCX0N
CQoJfQ0KCgkvLyBBbHdheXMgZGVzdHJveSBjdXJzb3IKCWlkY1BpcGVsaW5lLmRlc3Ryb3koKTs=
</value>
</Values>
