<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">compareInts</value>
  <value name="encodeutf8">true</value>
  <value name="body">DQpJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwppbnQgZmly
c3ROdW1iZXIgPSAwOwppbnQgc2Vjb25kTnVtYmVyID0gMDsKCmlmIChpZGNQaXBlbGluZS5maXJz
dCgiZmlyc3ROdW1iZXIiKSkKewoJZmlyc3ROdW1iZXIgPSBJbnRlZ2VyLnBhcnNlSW50KChTdHJp
bmcpaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKSk7Cn0KZWxzZQp7Cgl0aHJvdyBuZXcgU2VydmljZUV4
Y2VwdGlvbigiSW5wdXQgZmlyc3ROdW1iZXIgY2Fubm90IGJlIG51bGwhIik7Cn0KCmlmIChpZGNQ
aXBlbGluZS5maXJzdCgic2Vjb25kTnVtYmVyIikpCnsKCXNlY29uZE51bWJlciA9IEludGVnZXIu
cGFyc2VJbnQoKFN0cmluZylpZGNQaXBlbGluZS5nZXRWYWx1ZSgpKTsKfQplbHNlCnsKCXRocm93
IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKCJJbnB1dCBzZWNvbmROdW1iZXIgY2Fubm90IGJlIG51bGwh
Iik7Cn0KCg0KaWYgKGZpcnN0TnVtYmVyID09IHNlY29uZE51bWJlcikNCnsNCglpZGNQaXBlbGlu
ZS5pbnNlcnRBZnRlcigib3V0cHV0IiwgIjAiKTsKfQ0KZWxzZQ0Kew0KCWlmIChmaXJzdE51bWJl
ciA+IHNlY29uZE51bWJlcikNCgkJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoIm91dHB1dCIsICIx
Iik7CgllbHNlDQoJCWlkY1BpcGVsaW5lLmluc2VydEFmdGVyKCJvdXRwdXQiLCAiLTEiKTsKfSAN
CgovLyBDbGVhbiB1cCBJRGF0YSBjdXJzb3JzCmlkY1BpcGVsaW5lLmRlc3Ryb3koKTsK</value>
</Values>
