<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">bytesToStream</value>
  <value name="encodeutf8">true</value>
  <value name="body">CUlEYXRhQ3Vyc29yIGN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoKCWJ5dGVbXSBidWZm
ID0gbnVsbDsKCWludCBsZW47CglCeXRlQXJyYXlJbnB1dFN0cmVhbSBibG9ja1N0cmVhbSA9IG51
bGw7CgoJaWYgKGN1cnNvci5maXJzdCgiYnVmZmVyIikpCgl7CgkJYnVmZiA9IChieXRlW10pIGN1
cnNvci5nZXRWYWx1ZSgpOwoJfQoJZWxzZQoJewoJCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9u
KCJJbnB1dCBwYXJhbWV0ZXIgXCdidWZmZXJcJyB3YXMgbm90IGZvdW5kLiIpOwoJfQoJaWYgKGN1
cnNvci5maXJzdCgibGVuZ3RoIikpCgl7CgkJbGVuID0gSW50ZWdlci5wYXJzZUludCgoU3RyaW5n
KSBjdXJzb3IuZ2V0VmFsdWUoKSk7Cgl9CgllbHNlCgl7CgkJdGhyb3cgbmV3IFNlcnZpY2VFeGNl
cHRpb24oIklucHV0IHBhcmFtZXRlciBcJ2xlbmd0aFwnIHdhcyBub3QgZm91bmQuIik7Cgl9Cglj
dXJzb3IuZGVzdHJveSgpOwoKCWlmIChidWZmICE9IG51bGwpCgl7CgkJYmxvY2tTdHJlYW0gPSBu
ZXcgQnl0ZUFycmF5SW5wdXRTdHJlYW0oYnVmZiwgMCwgbGVuKTsKCX0gCgkvLyBlbHNlLCBuby1v
cDsKCgljdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCWN1cnNvci5sYXN0KCk7CgljdXJz
b3IuaW5zZXJ0QWZ0ZXIoImJsb2NrU3RyZWFtIiwgYmxvY2tTdHJlYW0pOwoJY3Vyc29yLmRlc3Ry
b3koKTs=</value>
</Values>
