<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">checkParameterValidity</value>
  <value name="encodeutf8">true</value>
  <value name="body">CglJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoJU3RyaW5n
IHN0clBhcmFtTmFtZSA9IG51bGw7CglTdHJpbmcgc3RyUGFyYW1WYWx1ZSA9IG51bGw7CglpZiAo
aWRjUGlwZWxpbmUuZmlyc3QoInBhcmFtTmFtZSIpKQoJewoJCXN0clBhcmFtTmFtZSA9IChTdHJp
bmcpaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsKCX0KCWVsc2UKCXsKCQl0aHJvdyBuZXcgU2Vydmlj
ZUV4Y2VwdGlvbiAoIlBhcmFtZXRlciBuYW1lIGNhbm5vdCBiZSBudWxsISIpOwoJfQoJaWYgKGlk
Y1BpcGVsaW5lLmZpcnN0KCJwYXJhbVZhbHVlIikpCgl7CgkJc3RyUGFyYW1WYWx1ZSA9IChTdHJp
bmcpaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsKCX0KCWVsc2UKCXsKCQl0aHJvdyBuZXcgU2Vydmlj
ZUV4Y2VwdGlvbiAoIlBhcmFtZXRlciB2YWx1ZSBjYW5ub3QgYmUgbnVsbCEiKTsKCX0KCglTdHJp
bmcgc3RyQWxsb3dlZFBhcmFtVmFsdWVzID0gKFN0cmluZylwcm9wZXJ0aWVzLmdldChzdHJQYXJh
bU5hbWUpOwoJU3RyaW5nVG9rZW5pemVyIHN0ID0gbmV3IFN0cmluZ1Rva2VuaXplcihzdHJBbGxv
d2VkUGFyYW1WYWx1ZXMsICIqIik7CgoJU3RyaW5nIHN0clZhbGlkID0gImZhbHNlIjsKCXdoaWxl
IChzdC5oYXNNb3JlRWxlbWVudHMoKSkKCXsKCQlTdHJpbmcgc3RyQWxsb3dlZFBhcmFtVmFsdWUg
PSAoU3RyaW5nKXN0Lm5leHRFbGVtZW50KCk7CgkJaWYgKHN0ckFsbG93ZWRQYXJhbVZhbHVlLmVx
dWFscyhzdHJQYXJhbVZhbHVlKSkKCQl7CgkJCXN0clZhbGlkID0gInRydWUiOwoJCQlicmVhazsK
CQl9Cgl9CgoJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoInZhbGlkIiwgc3RyVmFsaWQpOwoJaWRj
UGlwZWxpbmUuZGVzdHJveSgpOwo=</value>
</Values>
