<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">isAlphanumeric</value>
  <value name="encodeutf8">true</value>
  <value name="body">CklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CnBpcGVs
aW5lQ3Vyc29yLmZpcnN0KCAiaW5wdXQiICk7ClN0cmluZyBpbnB1dCA9IChTdHJpbmcpcGlwZWxp
bmVDdXJzb3IuZ2V0VmFsdWUoKTsKClN0cmluZyBpc0FscGhhbnVtZXJpYyA9ICJ0cnVlIjsKCmNo
YXIgYzsKZm9yIChpbnQgaSA9IDA7IGkgPCBpbnB1dC5sZW5ndGgoKTsgaSsrKQp7CgljID0gaW5w
dXQuY2hhckF0KGkpOwoJaWYgKChjIDwgJzAnIHx8IGMgPiAnWicpICYmIChjIDwgJ2EnIHx8IGMg
PiAneicpKQoJewoJCWlzQWxwaGFudW1lcmljID0gImZhbHNlIjsKCQlicmVhazsKCX0KfQoKcGlw
ZWxpbmVDdXJzb3IuaW5zZXJ0QWZ0ZXIoImlzQWxwaGFudW1lcmljIiwgaXNBbHBoYW51bWVyaWMp
OwpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7Cg==</value>
</Values>
