<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">stringToStream</value>
  <value name="encodeutf8">true</value>
  <value name="body">DQlJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KDQlpZGNQ
aXBlbGluZS5maXJzdCgic3RyaW5nIik7DQoJU3RyaW5nIHN0cmluZyA9IChTdHJpbmcpaWRjUGlw
ZWxpbmUuZ2V0VmFsdWUoKTsNCgoJU3RyaW5nQnVmZmVySW5wdXRTdHJlYW0gb3V0cHV0ID0gbmV3
IFN0cmluZ0J1ZmZlcklucHV0U3RyZWFtKHN0cmluZyk7DQoNCgl3aGlsZSAoaWRjUGlwZWxpbmUu
Zmlyc3QoInN0cmVhbSIpKQoJew0KCQlpZGNQaXBlbGluZS5kZWxldGUoKTsNCgl9DQoNCgkNDWlk
Y1BpcGVsaW5lLmxhc3QoKTsNCgkNT2JqZWN0IGlucHV0U3RyZWFtID0gb3V0cHV0Ow0KCQ1pZGNQ
aXBlbGluZS5pbnNlcnRBZnRlcigic3RyZWFtIiwgaW5wdXRTdHJlYW0gKTsNCgkNaWRjUGlwZWxp
bmUuZGVzdHJveSgpOw0K</value>
</Values>
