<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getSystemProperty</value>
  <value name="encodeutf8">true</value>
  <value name="body">LyoqIFNlcnZpY2UgaXMgZGVzaWduZWQgdG8gcmV0dXJuIHRoZSBzcGVjaWZpZWQgc3lzdGVtIHBy
b3BlcnR5LgogICoKICAqIEBhdXRob3IgUnlhbiBKb2huc3RvbiwgUHJvZmVzc2lvbmFsIFNlcnZp
Y2VzLCB3ZWJNZXRob2RzLCBJbmMuCiAgKiBAdmVyc2lvbiAxLjAKICAqIE1vZGlmaWVkIHRvIGNo
ZWNrIGZvciBleGlzdGluZyBvZiBwcm9wZXJ0eUxpc3QgYmVmb3JlIGRlbGV0ZSAoUm9uYWxkIEIp
CiAgKi8KCklEYXRhQ3Vyc29yIGhDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCmhDdXJz
b3IuZmlyc3QoInByb3BlcnR5TmFtZSIpOwpTdHJpbmcgcHJvcGVydHlOYW1lID0gKFN0cmluZylo
Q3Vyc29yLmdldFZhbHVlKCk7CgpTdHJpbmcgcHJvcGVydHkgPSBuZXcgU3RyaW5nKCk7Cgpwcm9w
ZXJ0eSA9IFN5c3RlbS5nZXRQcm9wZXJ0eShwcm9wZXJ0eU5hbWUsICJObyBwcm9wZXJ0eSBmb3Vu
ZCIpOwoKaWYgKGhDdXJzb3IuZmlyc3QoInByb3BlcnR5IikpCgloQ3Vyc29yLmRlbGV0ZSgpOwpo
Q3Vyc29yLmluc2VydEFmdGVyKCJwcm9wZXJ0eSIsIHByb3BlcnR5KTsK</value>
</Values>
