<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">extractCertificate</value>
  <value name="encodeutf8">true</value>
  <value name="body">CUlEYXRhQ3Vyc29yIGlkY1BpcGVsaW5lID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CglieXRlW10g
Y2VydGlmaWNhdGUgPSBudWxsOwoJaWYgKGlkY1BpcGVsaW5lLmZpcnN0KCJjZXJ0aWZpY2F0ZSIp
KQoJewoJCWNlcnRpZmljYXRlID0gKGJ5dGVbXSlpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOwoJfQoJ
dHJ5Cgl7CgkJQnl0ZUFycmF5SW5wdXRTdHJlYW0gaW5TdHJlYW0gPSBuZXcgQnl0ZUFycmF5SW5w
dXRTdHJlYW0oY2VydGlmaWNhdGUpOwoJCiAJCUNlcnRpZmljYXRlRmFjdG9yeSBjZiA9IENlcnRp
ZmljYXRlRmFjdG9yeS5nZXRJbnN0YW5jZSgiWC41MDkiKTsKIAkJWDUwOUNlcnRpZmljYXRlIGNl
cnQgPSAoWDUwOUNlcnRpZmljYXRlKWNmLmdlbmVyYXRlQ2VydGlmaWNhdGUoaW5TdHJlYW0pOwog
CQlpblN0cmVhbS5jbG9zZSgpOwoKCQlTdHJpbmcgc3ViamVjdEROID0gKChQcmluY2lwYWwpKGNl
cnQuZ2V0U3ViamVjdEROKCkpKS5nZXROYW1lKCk7CgkJU3RyaW5nIGlzc3VlckROID0gKChQcmlu
Y2lwYWwpKGNlcnQuZ2V0SXNzdWVyRE4oKSkpLmdldE5hbWUoKTsKCQlTdHJpbmcgaXNzdWVyU04g
PSBTdHJpbmcudmFsdWVPZihjZXJ0LmdldFNlcmlhbE51bWJlcigpLmludFZhbHVlKCkpOwoJCURh
dGUgbm90QmVmb3JlID0gY2VydC5nZXROb3RCZWZvcmUoKTsKCQlEYXRlIG5vdEFmdGVyID0gY2Vy
dC5nZXROb3RBZnRlcigpOwoKCQlpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigic3ViamVjdEROIiwg
c3ViamVjdEROKTsKCQlpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigiaXNzdWVyRE4iLCBpc3N1ZXJE
Tik7CgkJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoImlzc3VlclNOIiwgaXNzdWVyU04pOwoJCWlk
Y1BpcGVsaW5lLmluc2VydEFmdGVyKCJub3RCZWZvcmUiLCBub3RCZWZvcmUudG9TdHJpbmcoKSk7
CgkJaWRjUGlwZWxpbmUuaW5zZXJ0QWZ0ZXIoIm5vdEFmdGVyIiwgbm90QWZ0ZXIudG9TdHJpbmco
KSk7Cgl9CgljYXRjaChFeGNlcHRpb24gZSkKCXsKCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlv
biAoZS5nZXRNZXNzYWdlKCkpOwoJfQoJZmluYWxseQoJewoJCWlkY1BpcGVsaW5lLmRlc3Ryb3ko
KTsKCX0K</value>
</Values>
