<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getBasename</value>
  <value name="encodeutf8">true</value>
  <value name="body">CUlEYXRhQ3Vyc29yIGlkY1BpcGVsaW5lID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7CgoJU3RyaW5n
IGZpbGVuYW1lID0gbnVsbDsKCWlmIChpZGNQaXBlbGluZS5maXJzdCgiZmlsZW5hbWUiKSkKCXsK
CQlmaWxlbmFtZSA9IChTdHJpbmcpIGlkY1BpcGVsaW5lLmdldFZhbHVlKCk7Cgl9CgllbHNlCgl7
CgkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIklucHV0IHBhcmFtZXRlciBcJ2ZpbGVuYW1l
XCcgd2FzIG5vdCBmb3VuZC4iKTsKCX0KCglGaWxlIGZpbGUgPSBuZXcgRmlsZShmaWxlbmFtZSk7
CglTdHJpbmcgYmFzZW5hbWUgPSBmaWxlLmdldE5hbWUoKTsKCglpZGNQaXBlbGluZS5sYXN0KCk7
CglpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigiYmFzZW5hbWUiLCBiYXNlbmFtZSk7ICAKCWlkY1Bp
cGVsaW5lLmRlc3Ryb3koKTs=</value>
</Values>
