<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">compareFloats</value>
  <value name="encodeutf8">true</value>
  <value name="body">ClN0cmluZyBzMSA9ICIiOwpTdHJpbmcgczIgPSAiIjsKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJz
b3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKaWYgKHBpcGVsaW5lQ3Vyc29yLmZpcnN0KCAiZmly
c3ROdW1iZXIiICkpCnsKCXMxID0gKFN0cmluZylwaXBlbGluZUN1cnNvci5nZXRWYWx1ZSgpOwp9
CmVsc2UKewoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIklucHV0IGZpcnN0TnVtYmVyIGNh
bm5vdCBiZSBudWxsISIpOwp9CgppZiAocGlwZWxpbmVDdXJzb3IuZmlyc3QoICJzZWNvbmROdW1i
ZXIiICkpCnsKCXMyID0gKFN0cmluZylwaXBlbGluZUN1cnNvci5nZXRWYWx1ZSgpOwp9CmVsc2UK
ewoJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIklucHV0IHNlY29uZE51bWJlciBjYW5ub3Qg
YmUgbnVsbCEiKTsKfQoKZmxvYXQgZmlyc3ROdW1iZXIgPSBGbG9hdC52YWx1ZU9mKHMxKS5mbG9h
dFZhbHVlKCk7CmZsb2F0IHNlY29uZE51bWJlciA9IEZsb2F0LnZhbHVlT2YoczIpLmZsb2F0VmFs
dWUoKTsKCmlmIChmaXJzdE51bWJlciA9PSBzZWNvbmROdW1iZXIpCnsKCXBpcGVsaW5lQ3Vyc29y
Lmluc2VydEFmdGVyKCJvdXRwdXQiLCAiMCIpOwp9CmVsc2UKewoJaWYgKGZpcnN0TnVtYmVyID4g
c2Vjb25kTnVtYmVyKQoJCXBpcGVsaW5lQ3Vyc29yLmluc2VydEFmdGVyKCJvdXRwdXQiLCAiMSIp
OwoJZWxzZQoJCXBpcGVsaW5lQ3Vyc29yLmluc2VydEFmdGVyKCJvdXRwdXQiLCAiLTEiKTsKfSAK
</value>
</Values>
