<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">truncateNumber</value>
  <value name="encodeutf8">true</value>
  <value name="body">CglJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoJaWYgKCFp
ZGNQaXBlbGluZS5maXJzdCgibnVtYmVyIikpCgl7CgkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRp
b24oImlucHV0IG51bWJlciB3YXMgbnVsbCEiKTsKCX0KCglTdHJpbmcgc3RyTnVtYmVyID0gKFN0
cmluZylpZGNQaXBlbGluZS5nZXRWYWx1ZSgpOwoJZG91YmxlIGRibE51bWJlciA9IERvdWJsZS5w
YXJzZURvdWJsZShzdHJOdW1iZXIpOwoKCglpZiAoaWRjUGlwZWxpbmUuZmlyc3QoInByZWNpc2lv
biIpKQoJewoJCVN0cmluZyBzdHJQcmVjaXNpb24gPSAoU3RyaW5nKWlkY1BpcGVsaW5lLmdldFZh
bHVlKCk7CgkJZG91YmxlIGRibFByZWNpc2lvbiA9IERvdWJsZS5wYXJzZURvdWJsZShzdHJQcmVj
aXNpb24pOwoKCQlkb3VibGUgZGJsTXVsRGl2RmFjdG9yID0gamF2YS5sYW5nLk1hdGgucG93KDEw
LCBkYmxQcmVjaXNpb24pOwoJCWRvdWJsZSBkYmxUcnVuY2F0ZWROdW1iZXIgPSBqYXZhLmxhbmcu
TWF0aC5mbG9vcihkYmxOdW1iZXIgKiBkYmxNdWxEaXZGYWN0b3IpIC8gZGJsTXVsRGl2RmFjdG9y
OwoKCQlpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigidHJ1bmNhdGVkTnVtYmVyIiwgRG91YmxlLnRv
U3RyaW5nKGRibFRydW5jYXRlZE51bWJlcikpOwoKCX0KCWVsc2UKCXsKCQlpZGNQaXBlbGluZS5p
bnNlcnRBZnRlcigidHJ1bmNhdGVkTnVtYmVyIiwgc3RyTnVtYmVyKTsKCgl9CgoJaWRjUGlwZWxp
bmUuZGVzdHJveSgpOw==</value>
</Values>
