<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">removeLineSeparators</value>
  <value name="encodeutf8">true</value>
  <value name="body">CglJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoKCVN0cmlu
ZyBpblN0cmluZyA9IG51bGw7CglpZiAoaWRjUGlwZWxpbmUuZmlyc3QoImluU3RyaW5nIikpCgl7
CgkJaW5TdHJpbmcgPSAoU3RyaW5nKWlkY1BpcGVsaW5lLmdldFZhbHVlKCk7Cgl9CgllbHNlCgl7
CgkJLy8gSW5wdXQgc3RyaW5nIGlzIG51bGwuICBEbyBub3RoaW5nCgkJcmV0dXJuOwoJfQoKCVN0
cmluZ0J1ZmZlciB0ZW1wU3RyaW5nID0gbmV3IFN0cmluZ0J1ZmZlcihpblN0cmluZy5sZW5ndGgo
KSk7CglTdHJpbmcgb3V0U3RyaW5nID0gIiI7CgoJLy8gU3RyaXAgc3RyaW5nIG9mIGFsbCAiXHJc
biIgb2NjdXJyZW5jZXMKICAgIGZvcihpbnQgaT0wO2k8aW5TdHJpbmcubGVuZ3RoKCk7aSsrKQoJ
ewoJCWNoYXIgYzsKCQljID0gaW5TdHJpbmcuY2hhckF0KGkpOwoJCWlmIChjICE9ICdccicgJiYg
YyAhPSAnXG4nKQoJCQl0ZW1wU3RyaW5nLmFwcGVuZChjKTsKICAgIH0KCgoJaWRjUGlwZWxpbmUu
aW5zZXJ0QWZ0ZXIoIm91dFN0cmluZyIsIHRlbXBTdHJpbmcudG9TdHJpbmcoKSk7CgovLyBDbGVh
biB1cCBJRGF0YSBjdXJzb3JzCglpZGNQaXBlbGluZS5kZXN0cm95KCk7Cg==</value>
</Values>
