<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">checkFileExistence</value>
  <value name="encodeutf8">true</value>
  <value name="body">DQpJRGF0YUN1cnNvciBpZGNQaXBlbGluZSA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwpTdHJpbmcg
c3RyUGF0aG5hbWUgPSAiIjsKaWYgKGlkY1BpcGVsaW5lLmZpcnN0KCJwYXRobmFtZSIpKQp7Cglz
dHJQYXRobmFtZSA9IChTdHJpbmcpaWRjUGlwZWxpbmUuZ2V0VmFsdWUoKTsKCUZpbGUgcGF0aCA9
IG5ldyBGaWxlKHN0clBhdGhuYW1lKTsNCg0KCS8vICoqKiBDaGVjayBpZiBwYXRoIGlzIG9uIHRo
ZSBhbGxvd2VkIGxpc3QgKioqCgl0cnkKCXsKCQlpZiAoIWNoZWNrUGF0aFZhbGlkaXR5KHN0clBh
dGhuYW1lLCAicmVhZCIpKQoJCXsKCQkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oIlNwZWNp
ZmllZCBwYXRoIGlzIG5vdCBvbiB0aGUgcmVhZCBhbGxvd2VkIGxpc3QgaW4gdGhlIFBTVXRpbGl0
aWVzIGNvbmZpZ3VyYXRpb24gZmlsZSEiKTsKCQl9Cgl9CgljYXRjaCAoRXhjZXB0aW9uIGUpCgl7
CgkJdGhyb3cgbmV3IFNlcnZpY2VFeGNlcHRpb24oZS5nZXRNZXNzYWdlKCkpOwoJfQoJLy8gKioq
IEVuZCBjaGVjayAqKioKCglpZiAoIXBhdGguZXhpc3RzKCkpDQoJCWlkY1BpcGVsaW5lLmluc2Vy
dEFmdGVyKCJleGlzdHM/IiwgImZhbHNlIik7DQoJZWxzZQ0KCQlpZGNQaXBlbGluZS5pbnNlcnRB
ZnRlcigiZXhpc3RzPyIsICJ0cnVlIik7IA0KCglpZiAocGF0aC5pc0RpcmVjdG9yeSgpKQoJCWlk
Y1BpcGVsaW5lLmluc2VydEFmdGVyKCJpc0RpcmVjdG9yeSIsICJ0cnVlIik7DQoJZWxzZQoJCWlk
Y1BpcGVsaW5lLmluc2VydEFmdGVyKCJpc0RpcmVjdG9yeT8iLCAiZmFsc2UiKTsNCn0KZWxzZQp7
CglpZGNQaXBlbGluZS5pbnNlcnRBZnRlcigiZXhpc3RzPyIsICJmYWxzZSIpOwoJaWRjUGlwZWxp
bmUuaW5zZXJ0QWZ0ZXIoImlzRGlyZWN0b3J5PyIsICJmYWxzZSIpOwp9CgppZGNQaXBlbGluZS5k
ZXN0cm95KCk7DQo=</value>
</Values>
