<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">deleteFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">CUlEYXRhQ3Vyc29yIGN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOwoKCVN0cmluZyBmaWxl
bmFtZSA9IG51bGw7CglpZiAoY3Vyc29yLmZpcnN0KCJmaWxlbmFtZSIpKQoJewoJCWZpbGVuYW1l
ID0gKFN0cmluZykgY3Vyc29yLmdldFZhbHVlKCk7Cgl9CgllbHNlCgl7CgkJdGhyb3cgbmV3IFNl
cnZpY2VFeGNlcHRpb24oIklucHV0IHBhcmFtZXRlciBcJ2ZpbGVuYW1lXCcgd2FzIG5vdCBmb3Vu
ZC4iKTsKCX0KCWN1cnNvci5kZXN0cm95KCk7CgoNCS8vICoqKiBDaGVjayBpZiBwYXRoIGlzIG9u
IHRoZSBhbGxvd2VkIGxpc3QgKioqCgl0cnkKCXsKCQlpZiAoIWNoZWNrUGF0aFZhbGlkaXR5KGZp
bGVuYW1lLCAiZGVsZXRlIikpCgkJewoJCQl0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiU3Bl
Y2lmaWVkIHBhdGggaXMgbm90IG9uIHRoZSBkZWxldGUgYWxsb3dlZCBsaXN0IGluIHRoZSBQU1V0
aWxpdGllcyBjb25maWd1cmF0aW9uIGZpbGUhIik7CgkJfQoJfQoJY2F0Y2ggKEV4Y2VwdGlvbiBl
KQoJewoJCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKGUuZ2V0TWVzc2FnZSgpKTsKCX0KCS8v
ICoqKiBFbmQgY2hlY2sgKioqCgoJRmlsZSBmaWxlID0gbmV3IEZpbGUoZmlsZW5hbWUpOwoJbG9u
ZyBsZW4gPSBmaWxlLmxlbmd0aCgpOwoJYm9vbGVhbiBiID0gZmlsZS5kZWxldGUoKTsKCgljdXJz
b3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCWN1cnNvci5sYXN0KCk7CgljdXJzb3IuaW5zZXJ0
QWZ0ZXIoImRlbGV0ZVN0YXR1cyIsICIiICsgYik7CgljdXJzb3IuaW5zZXJ0QWZ0ZXIoImxlbmd0
aCIsICIiICsgbGVuKTsKCWN1cnNvci5kZXN0cm95KCk7</value>
</Values>
