<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">lookingAt</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gVG9uaSBJbW1vcmRpbm8KCi8vIHBpcGVsaW5lCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29y
ID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7ClN0cmluZyByZWdleCA9IElEYXRhVXRpbC5nZXRTdHJp
bmcoIHBpcGVsaW5lQ3Vyc29yLCAicmVnZXgiICk7ClN0cmluZyBpbnB1dCA9IElEYXRhVXRpbC5n
ZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiaW5wdXQiICk7CnBpcGVsaW5lQ3Vyc29yLmRlc3Ry
b3koKTsKClN0cmluZyBtYXRjaCA9ICJmYWxzZSI7CgpQYXR0ZXJuIHBhdHRlcm4gPSBQYXR0ZXJu
LmNvbXBpbGUocmVnZXgpOwpNYXRjaGVyIG1hdGNoZXIgPSBwYXR0ZXJuLm1hdGNoZXIoaW5wdXQp
OwoKaWYgKG1hdGNoZXIubG9va2luZ0F0KCkpCnsKCW1hdGNoID0gInRydWUiOwp9CgoKLy8gcGlw
ZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigp
OwpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAibWF0Y2giLCBtYXRjaCApOwpwaXBl
bGluZUN1cnNvcl8xLmRlc3Ryb3koKTsK</value>
</Values>
